### ISSUE TITLE
Unexpected behavior of idle event callback

### ISSUE THREAD

**Issue by madagra** [OpenMPToolsInterface/LLVM-openmp#40]
The time spent by OpenMP threads (except master thread) outside parallel regions seems to be recorded inside a `sync_region_wait` event instead of an `idle` event. 
A simple code snippet reproducing the issue is the following:
```
    #pragma omp parallel num_threads(4)
    {
        int tid = omp_get_thread_num();
        if (0 == tid) {
            printf("[region1] number of OpenMP threads: %d\n",omp_get_num_threads());
        }
        sleep(4);
    }
    sleep(6);
```
If measuring the time spent in the `idle` and `sync_wait_region` callbacks, one can notice that the last 6 seconds `sleep` is accounted within the `sync_region_wait` event. Shouldn't this time be accounted within an `idle` event? According to my understanding of the OMPT specification, the `idle` event accounts for waiting time outside OpenMP parallel regions, whereas `sync_region_wait` accounts for barrier time inside parallel regions. A reproducer of this issue can be found [here](https://github.com/madagra/OMPT-issues/tree/master/idle_event_scope_issue).

**Comment by yanyh15** [comment]
This is the same issue as
https://github.com/OpenMPToolsInterface/LLVM-openmp/issues/25

Basically a worker thread may enter idle state before the sync_region_wait_end of the join barrier and it would not trigger that sync_region_wait_end until the master reaches the next parallel region and release/wake up that thread by re-engaging that worker thread again, if it will be re-engaged.

**Comment by jprotze** [comment]
In the OpenMP tools working group we decided to remove this callback at all, since it creates wrong expectations, which cannot be met since a parallel team might create explicit tasks at any time and therefore worker threads and their implicit tasks cannot leave the team before the master finishes the barrier. 
In a valid runtime implementation, the worker threads might not learn that they were idleing until they are recruited by the next team.

This callback will be removed in OpenMP 5.0!

**Comment by madagra** [comment]
Thank you for the explanation. Removing this callback is the logical choice.
