### ISSUE TITLE
Segmentation Fault on "parallel_data" in ompt_callback_implicit_task

### ISSUE THREAD

**Issue by simoatze** [OpenMPToolsInterface/LLVM-openmp#9]
@jprotze After updating the runtime with your last two commits I am getting an error when accessing the "parallel_data" in the ompt_callback_implicit_task (endpoint=ompt_scope_end).

I did some changes on my code so I thought it was a problem in my library, but if I reset to [17c90d5](https://github.com/OpenMPToolsInterface/LLVM-openmp/commit/17c90d56afbceb0dfc7a8c6f1250a2cc38959cee) I don't get any seg fault.

**Comment by simoatze** [comment]
@jprotze In any of the OpenMP spec with OMPT that I have the "ompt_callback_implicit_task_t" does not have the "team_size". Where do I find the most updated spec? Thanks!

I was missing that param but that did not resolve the problem, still getting segmentation fault.
I'll look more into it, to see if it's a runtime problem or I have some other error in my code.

**Comment by jprotze** [comment]
In this case, we already implemented changes that are not yet finally ratified by the language commitee. For a reference tool implementation please consult [callback.h](https://github.com/OpenMPToolsInterface/LLVM-openmp/blob/towards_tr4/runtime/test/ompt/callback.h).

**Comment by jprotze** [comment]
I think I understood your problem:
The implicit-task-end event is called after the final barrier. At this time the team is already gone. If you need the team data, store a pointer in implicit-task-begin and do ref-counting on the team object.

**Comment by jprotze** [comment]
After consulting the OpenMP spec, I decided to provide the parallel_data for now (as in latest commit).
You need to be aware, that this is a copy of the parallel_data value. Changing the value in parallel-end has no effect!

The basic problem (at tool side) still exist: implicit-task-end is concurrent to parallel-end. If you free parallel_data in parallel-end, and access parallel_data in implicit-task-end, you access after free.

For above reasons, I proposed to change the OpenMP spec, so that worker threads would legally provide NULL in implicit-task-end.

**Comment by simoatze** [comment]
@jprotze I see the problem, what I want to do is basically to identify if the implicit task end is actually the end of the task (per thread) of the outer parallel region. So I just generate a parallel id in "implicit task begin" and store it in "parallel_data->value" and in a TLS variable. When I reach the "implicit task end" I compare "parallel_data->value" with my TLS variable, if they are the same means that that's the task of the outer parallel region, so after that basically the program goes back to sequential.

Does it make sense? Do you see a better way to do this?

**Comment by jmellorcrummey** [comment]
Simone, I don't think that you need the parallel_data value for this. Upon an implicit_task begin, you can increment a counter in TLS. Upon implicit_task_end, you can decrement the counter. When the counter goes back to 0, the thread is outside any parallel region, i.e., back to sequential for the main thread or returning to idle for a worker thread.

**Comment by simoatze** [comment]
John, I just realized that, thanks a lot!

**Comment by simoatze** [comment]
My problem is that I use the unique parallel ID (generated inside "paralllel begin") as a filename (concatenated with the thread ID) and at the end of an outer parallel region I need to close those files. So I still need to retrieve that value.

**Comment by jmellorcrummey** [comment]
Can't you record the id/filename in TLS when incrementing a TLS counter from 0 to 1  and then close the file when you decrement the TLS counter from 1 to 0?

**Comment by simoatze** [comment]
The thing I am tracing information per outer parallel region and having a unique parallel id as filename allows to distinguish all the outer parallel regions. If I increment and decrement those number will be always the same per parallel region, so I guess I need another TLS counter that I keep incrementing maybe?

**Comment by jmellorcrummey** [comment]
I was thinking that you would use the  runtime entry point known as ompt_get_unique_id with type signature 
`typedef` uint64_t (*ompt_get_unique_id_t)(void);
to generate a unique parallel id for a parallel region when you enter the parallel region. You can then record that in TLS. You keep a **separate** counter in TLS that you increment and decrement as you enter and leave a parallel region.  I would guess that you want to store the information about the file in the parallel_data field for the region so that all threads within the region will have access to the file. 
When the master thread leaves the outermost parallel region, you close the file.

**Comment by simoatze** [comment]
I actually need a file per thread, so basically I will have file_{tid}_{parallel_id}. For example if I have 4 threads I will have 4 different files, but all the files refer to the same "parallel_id". So I generate the parallel_id when the parallel region starts. In order to have that parallel_id I store the unique parallel_id in "parallel_data->value", when the implicit task starts I store the "parallel_data->value" in "task_data->value" so that when I hit the "implicit task end" I can retrieve the same value from "task_data->value" and I avoid the seg fault in case the parallel_data is already gone. Would this work?

**Comment by jmellorcrummey** [comment]
That's roughly what I had in mind. You could also store the parallel_data->value in a TLS variable inside your tool rather than in the implicit task data. I think both strategies should work.

**Comment by jprotze** [comment]
For TLS, ompt_get_thread_data is recommended. You can allocate a per thread-structure in ompt_callback_thread_begin, store a thread-id in there and use it for thread local data.

**Comment by jprotze** [comment]
ompt_callback_implicit_task is now specified to deliver parallel_data=NULL for the end-event.
